import { z } from "zod"

/**
 * @route POST /auth/rescuer/create
 * @description Creates a new rescuer
 * @access public
 * @requires id (autogenerated), name, phone, email, city, state, country, skills
 */

const rescuerSchema = z.object({
  id: z.string().default(nanoid()),
})

async function createNewRescuer() {
  try {
  } catch (error) {}
}
